### ISSUE TITLE
Allow the use of encrypted wallet with thick client for passwordless login

### ISSUE THREAD

**Issue by walkabout21** [radbrt/target-oracle#13]
SqlAlchemy with cx_oracle supports logging into oracle db with an encrypted wallet instead of password.  The target logic should be able to be adjusted minimally to allow the use of the wallet via a tool like meltano.

**Comment by radbrt** [comment]
Hi @walkabout21! I tried the encrypted wallet thing once, many years ago. As far as I remember, this was specified as a parameter to the connection string? Something like `oracle://user@some.host.com/ora?wallet=/home/me/.ssh/my_wallet.zip` or something?

I gave this half a thought when I wrote the target, and as far as I could tell it should be possible to do this by specifying the `sqlalchemy_url` parameter directly. But I remember someone else mentioned this issue too a while back, are you able to pinpoint what needs to be done, or provide me a better example of how to connect to Oracle with a wallet in sqlalchemy?

**Comment by walkabout21** [comment]
So solved this on my own.  The problem was that sqlalchemy and cx_oracle docs are a little confusing (as is Oracle in general) when it comes to wallet and proxy user authentication.  We use a wallet auth with a proxy user set up as a host in tns names.  
I tried passing the sqlalchemy URI but I was getting a null password error. I thought this was a problem with identifying the wallet location and or oracle home.  We have tns and sqlnet vars set up properly on our container so technically we should be able to just pass 
```
oracle+cx_oracle://user@mynetalias
```
In straight cx_oracle this would look something like this 
```python
# External Authentication with proxy
connection = cx_Oracle.connect(user="[mysessionuser]", dsn="mynetalias",
                               encoding="UTF-8")
# PROXY_USER:   MYUSER
# SESSION_USER: MYSESSIONUSER
```
For reasons I am not completely clear on, we have to pass the user with brackets like this
```
oracle+cx_oracle://[user]@tns_host
```

I'm assuming the brackets indicate there is no password.
